spring.application.name=schoolmanagement

spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.startup.command=up
spring.docker.compose.shutdown.command=down
spring.docker.compose.shutdown.timeout=30s
spring.docker.compose.skip.in-tests=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

